from distutils.core import setup
import py2exe

# The main script of your game (change this to your main script's name)
main_script = "project.py"

modules_list = ["project", "game", "asteroid", "laser", "button"]

# List of other files and directories to include in the executable
# Here, we include all files and subdirectories in the 'resources' directory
data_files = [(".", ["a-hero-of-the-80s-126684.mp3", "background_image.png", "controls.png", "difficulty_select.png", "instructions.png", "high_score.png", "large_asteroid.png", "laser_bullet.png", "medium_asteroid.png", "normal.png", "pause.png", "play.png", "potential_character.png", "quit.png", "resume.png", "retry.png", "score.png", "small_asteroid.png", "yasmin.png"])]

# Options for py2exe
options = {
    "py2exe": {
        "bundle_files": 1,  # 1 = Bundle all files into the executable
        "compressed": True,  # Compress the executable
        "optimize": 2,  # Optimize generated bytecode
        "includes": ["pygame", "random", "time", ],  # List any additional modules you need
    }
}

setup(
    windows=[{"script": "project.py"}],
    py_modules=modules_list,
    data_files=data_files,
    options=options,
)
